version: 2.1
parameters:
  test_env:
    type: enum
    enum: ["dev", "tst", "qa", "prd"]
    default: "tst"

  cucumber_tag:
    type: enum
    enum: [ "@email_validation", "@positive_flow", "@negative_flow" ]
    default: "@email_validation"

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout
      - run:
            name: Display selected execution parameters
            command: |
              echo "Environment: << pipeline.parameters.test_env >>"
              echo "Cucumber tag: << pipeline.parameters.cucumber_tag >>"

      - run:
          name: Run API tests and generate cucumber report
          command: mvn clean verify -P<< pipeline.parameters.test_env >> -Dcucumber.filter.tags="<< pipeline.parameters.cucumber_tag >>"

      - store_artifacts:
          path: target

workflows:
  version: 2
  build_and_test:
    jobs:
      - build